library(bnlearn)
bl.alarm <- model2network('[Burglar][Whale][Earthquake][Alarm|Burglar:Earthquake:Whale][News|Earthquake][Watson|Alarm]')
plot(bl.alarm)
modified.alarm <- drop.arc(bl.alarm, "Whale", "Alarm")
modified.alarm <- reverse.arc(modified.alarm , "Alarm", "Burglar")
modified.alarm <- set.arc(modified.alarm, "Whale", "Burglar")
plot(modified.alarm)
data("learning.test")
str(learning.test)
pdag=gs(learning.test)
pdag
plot(pdag)
score(set.arc(pdag, from = "A", to = "B"), learning.test)
score(set.arc(pdag, from = "B", to = "A"), learning.test)
dag = pdag2dag(pdag, ordering = c("A", "B", "C", "D", "E", "F"))
par(mfrow=c(1,2))
plot(pdag)
plot(dag)
dag
fit = bn.fit(dag, learning.test)
fit
bn.fit.barchart(fit$D)
bn.fit.dotplot(fit$D)
data(gaussian.test)
str(gaussian.test)
pdag = gs(gaussian.test)
pdag
undirected.arcs(pdag)
dag = set.arc(pdag, "D", "B")
par(mfrow = c(1,2))
plot(pdag)
plot(dag)
fit = bn.fit(dag, gaussian.test)
fit
bn.fit.qqplot(fit)
bn.fit.xyplot(fit)
bn.fit.histogram(fit)
data("clgaussian.test")
str(clgaussian.test)
dag=gs(clgaussian.test)
dag
plot(dag)
dag = set.arc(dag, "H", "D")
dag = set.arc(dag, "D", "E")
dag = set.arc(dag, "E", "G")
dag = set.arc(dag, "D", "G")
plot(dag)
fit = bn.fit(dag, clgaussian.test)
fit